### ISSUE TITLE
Enemy evolution factors don't change from default

### ISSUE THREAD

**Issue by FRodrigues42** [TheSAguy/Natural_Evolution_Modules#15]
Proof: [https://i.imgur.com/eyAry6B.png](https://i.imgur.com/eyAry6B.png)
In the natural evolution expansion module, in data-final-fixes.lua you have:

```
if NEConfig.EvolutionFactor then
    if NEConfig.mod.DyTechWar and NEConfig.DyTechWar_Evo_override then
```

Shouldn't be:

```
if NEConfig.EvolutionFactor then
    if (not NEConfig.mod.DyTechWar) or (NEConfig.mod.DyTechWar and NEConfig.DyTechWar_Evo_override) then
```

result of my modification: [https://i.imgur.com/STPwohh.png](https://i.imgur.com/STPwohh.png)

**Comment by TheSAguy** [comment]
Thanks, made this update.
